import Head from 'next/head';
import LayoutAdmin from '@/layout/LayoutAdmin/LayoutAdmin';
import PromotionManage from '@/components/page/Admin/PromotionManage/PromotionManage';

const title = 'Quản lý mã khuyến mãi';
export default function Promotion() {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <NewsManage /> */}
            <PromotionManage />
        </>
    );
}
Promotion.getLayout = function getLayout(page) {
    return (
        <LayoutAdmin admin title={title}>
            {page}
        </LayoutAdmin>
    );
};
