import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
// import HomePage from "@/components/page/HomePage";
import Header from "@/components/common/Header";

export default function ListFilm() {
    return (
        <>
            <Head>
                <title>Danh sách phim</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            {/* <ListFilmPage /> */}
        </>
    );
}
