import Head from "next/head";
import LayoutUser from "@/layout/LayoutUser/LayoutUser";
import ListFilmPage from "@/components/page/User/ListFilmPage";
export default function ListFilm() {
    return (
        <>
            <Head>
                <title>Danh sách phim</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ListFilmPage />
        </>
    );
}
ListFilm.getLayout = function getLayout(page) {
    return <LayoutUser>{page}</LayoutUser>;
};
