import Head from 'next/head';
import LayoutAdmin from '@/layout/LayoutAdmin/LayoutAdmin';
import AllBookingPage from '@/components/page/User/AllBooking';

const title = 'Lịch sử đặt phòng';
export default function AllBooking() {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AllBookingPage />
        </>
    );
}
AllBooking.getLayout = function getLayout(page) {
    return (
        <LayoutAdmin user dark title={title}>
            {page}
        </LayoutAdmin>
    );
};
