import Head from 'next/head';
import OverviewPage from '@/components/page/User/OverviewPage';
import LayoutAdmin from '@/layout/LayoutAdmin/LayoutAdmin';

const title = 'Tổng quan tài khoản';
export default function Profile() {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <OverviewPage />
        </>
    );
}
Profile.getLayout = function getLayout(page) {
    return (
        <LayoutAdmin user dark title={title}>
            {page}
        </LayoutAdmin>
    );
};
