import Head from 'next/head';
import LayoutUser from '@/layout/LayoutUser/LayoutUser';
import ComboPage from '@/components/page/User/ComboPage';
export default function Combo() {
    return (
        <>
            <Head>
                <title>Combo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ComboPage />
        </>
    );
}
Combo.getLayout = function getLayout(page) {
    return <LayoutUser>{page}</LayoutUser>;
};
