export const PATH = {
    Home: '/',
    Login: '/auth/login',
    Register: '/auth/register',
    ForgotPassword: '/auth/forgotPassword',
    Overview: '/overview',
    Account: '/account',
    AccountManagement: '/admin/account',
    InvoiceDetail: '/invoiceDetail',
    InvoiceManagement: '/admin/invoice',
    ListFilm: '/listFilm',
    FilmManagement: '/admin/film',
    BookRoom: '/bookRoom',
    BookRoomManagement: '/admin/booking',
    News: '/news',
    NewsManagement: '/admin/news',
    Combo: '/combo',
    ComboManagement: '/admin/combo',
    Locations: '/locations',
    LocationsManagement: '/admin/locations',
    StatisicalManagement: '/admin/statisical',
    BannerManagement: '/admin/banner',
};
