import Head from 'next/head';
import { Inter } from 'next/font/google';
import HomePage from '@/components/page/User/HomePage';
import LayoutUser from '@/layout/LayoutUser/LayoutUser';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>BOX - Cafe Phim</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomePage />
        </>
    );
}

// Sử dụng getLayout để bọc trang trong LayoutUser
Home.getLayout = function getLayout(page) {
    return <LayoutUser>{page}</LayoutUser>;
};
