import Head from 'next/head';
import LayoutUser from '@/layout/LayoutUser/LayoutUser';
import DiscountPage from '@/components/page/User/DiscountPage';
export default function Discount() {
    return (
        <>
            <Head>
                <title>Khuyến mãi</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DiscountPage />
        </>
    );
}
Discount.getLayout = function getLayout(page) {
    return <LayoutUser>{page}</LayoutUser>;
};
