import Head from 'next/head';
import LayoutUser from '@/layout/LayoutUser/LayoutUser';
import LocationsPage from '@/components/page/User/LocationsPage';
export default function Locations() {
    return (
        <>
            <Head>
                <title>Locations</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LocationsPage />
        </>
    );
}
Locations.getLayout = function getLayout(page) {
    return <LayoutUser>{page}</LayoutUser>;
};
