import Head from 'next/head';
import LayoutAdmin from '@/layout/LayoutAdmin/LayoutAdmin';
import AccountPage from '@/components/page/User/AccountPage';

const title = 'Tài khoản';
export default function Account() {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AccountPage />
        </>
    );
}
Account.getLayout = function getLayout(page) {
    return (
        <LayoutAdmin user dark title={title}>
            {page}
        </LayoutAdmin>
    );
};
