// pages/bookRoom/[_id].js

import Head from 'next/head';
import LayoutUser from '@/layout/LayoutUser/LayoutUser';
import { useRouter } from 'next/router';
import { useBookingById } from '@/services/booking';
import BookingDetail from '@/components/page/User/BookingDetail/BookingDetail';
import LoadingFullPage from '@/components/common/LoadingFullPage/loadingFullPage'; // Thêm component loading

export default function Booking() {
    const router = useRouter();
    const { _id } = router.query;

    // Giả sử hook của bạn trả về cả isLoading
    const { booking, isLoading, isError } = useBookingById(_id);

    // Xử lý các trạng thái
    if (isLoading) {
        return <LoadingFullPage />; // Hiển thị loading trong khi chờ
    }

    if (isError || !booking) {
        return <div>Không tìm thấy đơn đặt phòng hoặc đã có lỗi xảy ra.</div>; // Hiển thị lỗi
    }

    // Chỉ render khi đã có dữ liệu booking
    return (
        <>
            <Head>
                <title>Chi tiết đặt phòng - {booking.id_booking}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BookingDetail booking={booking} />
        </>
    );
}

Booking.getLayout = function getLayout(page) {
    return <LayoutUser>{page}</LayoutUser>;
};
