import Head from "next/head";
import LayoutUser from "@/layout/LayoutUser/LayoutUser";
import { useRouter } from "next/router";
import { useBookingById } from "@/services/booking";
import BookingDetail from "@/components/page/User/BookingDetail/BookingDetail";
import dynamic from "next/dynamic";

const DynamicLoadingFullPage = dynamic(
    () => import("@/components/common/LoadingFullPage/loadingFullPage"),
    {
        ssr: false, // Tùy chọn QUAN TRỌNG nhất
        loading: () => null, // Optional: có thể trả về null hoặc một div trống trong lúc chờ load
    }
);
export default function Booking() {
    const router = useRouter();
    const { _id } = router.query;

    const { booking, isLoading, isError } = useBookingById(_id);

    if (isLoading) {
        return <DynamicLoadingFullPage />;
    }

    if (isError || !booking) {
        return <div>Không tìm thấy đơn đặt phòng hoặc đã có lỗi xảy ra.</div>;
    }

    return (
        <>
            <Head>
                <title>Chi tiết đặt phòng - {booking.id_booking}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BookingDetail booking={booking} />
        </>
    );
}

Booking.getLayout = function getLayout(page) {
    return <LayoutUser>{page}</LayoutUser>;
};
