import Head from 'next/head';
import LayoutUser from '@/layout/LayoutUser/LayoutUser';
import BookRoomPage from '@/components/page/User/BookRoomPage';
export default function BookRoom() {
    return (
        <>
            <Head>
                <title>Đặt phòng</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BookRoomPage />
        </>
    );
}
BookRoom.getLayout = function getLayout(page) {
    return <LayoutUser>{page}</LayoutUser>;
};
